export const mockJobs = [
  {
    id: 'JOB-001',
    title: 'Smithfield FC vs Rockdale FC',
    type: 'Post-Match',
    date: '9 Apr 2025',
    status: 'processing',
    icon: 'processing',
  },
  {
    id: 'JOB-002',
    title: 'Panthers FC vs Eagles FC',
    type: 'Pre-Match',
    date: '9 Apr 2025',
    status: 'approved',
    icon: 'approved',
  },
  {
    id: 'JOB-003',
    title: 'Marconi FC vs Sydney FC',
    type: 'Post-Match',
    date: '6 Apr 2025',
    status: 'completed',
    icon: 'completed',
  },
  {
    id: 'JOB-004',
    title: 'NPL NSW — Round 5',
    type: 'League Summary',
    date: '6 Apr 2025',
    status: 'completed',
    icon: 'completed',
  },
  {
    id: 'JOB-005',
    title: 'Blacktown City vs Penrith FC',
    type: 'Post-Match',
    date: '7 Apr 2025',
    status: 'failed',
    icon: 'failed',
  },
  {
    id: 'JOB-006',
    title: 'Parramatta FC vs Auburn FC',
    type: 'Pre-Match',
    date: '8 Apr 2025',
    status: 'approved',
    icon: 'approved',
  },
  {
    id: 'JOB-007',
    title: 'Western Sydney Wanderers vs Sydney FC',
    type: 'Post-Match',
    date: '5 Apr 2025',
    status: 'completed',
    icon: 'completed',
  },
  {
    id: 'JOB-008',
    title: 'NPL NSW — Round 6 Summary',
    type: 'League Summary',
    date: '7 Apr 2025',
    status: 'processing',
    icon: 'processing',
  },
];

