/**
 * Mock match data for Reporta AI.
 * Shape mirrors the expected Dribl API response for easy swapping later.
 */
export const mockMatches = [
  {
    id: "match-001",
    homeTeam: { name: "Man City", abbreviation: "MC", color: "#6366f1" },
    awayTeam: { name: "Arsenal", abbreviation: "AR", color: "#ef4444" },
    competition: "Premier League",
    date: "8 Apr 2025",
    time: "17:30",
    status: "live",
    score: { home: 1, away: 2 },
  },
  {
    id: "match-002",
    homeTeam: { name: "Barcelona", abbreviation: "BA", color: "#7c3aed" },
    awayTeam: { name: "Real Madrid", abbreviation: "RM", color: "#facc15" },
    competition: "La Liga",
    date: "9 Apr 2025",
    time: "21:00",
    status: "upcoming",
    score: null,
  },
  {
    id: "match-003",
    homeTeam: { name: "Bayern", abbreviation: "BA", color: "#dc2626" },
    awayTeam: { name: "Dortmund", abbreviation: "BV", color: "#eab308" },
    competition: "Bundesliga",
    date: "5 Apr 2025",
    time: "18:30",
    status: "completed",
    score: { home: 3, away: 1 },
  },
  {
    id: "match-004",
    homeTeam: { name: "PSG", abbreviation: "PS", color: "#1e40af" },
    awayTeam: { name: "Marseille", abbreviation: "OL", color: "#22d3ee" },
    competition: "Ligue 1",
    date: "6 Apr 2025",
    time: "20:45",
    status: "completed",
    score: { home: 2, away: 0 },
  },
  {
    id: "match-005",
    homeTeam: { name: "Liverpool", abbreviation: "LI", color: "#dc2626" },
    awayTeam: { name: "Man Utd", abbreviation: "MU", color: "#b91c1c" },
    competition: "Premier League",
    date: "10 Apr 2025",
    time: "14:00",
    status: "upcoming",
    score: null,
  },
  {
    id: "match-006",
    homeTeam: { name: "Real Madrid", abbreviation: "RM", color: "#facc15" },
    awayTeam: { name: "Atletico", abbreviation: "AT", color: "#ef4444" },
    competition: "UEFA Champions League",
    date: "11 Apr 2025",
    time: "21:00",
    status: "upcoming",
    score: null,
  },
  {
    id: "match-007",
    homeTeam: { name: "Chelsea", abbreviation: "CH", color: "#2563eb" },
    awayTeam: { name: "Spurs", abbreviation: "TO", color: "#1e3a5f" },
    competition: "Premier League",
    date: "4 Apr 2025",
    time: "16:00",
    status: "completed",
    score: { home: 1, away: 1 },
  },
  {
    id: "match-008",
    homeTeam: { name: "Arsenal", abbreviation: "AR", color: "#ef4444" },
    awayTeam: { name: "Liverpool", abbreviation: "LI", color: "#dc2626" },
    competition: "Premier League",
    date: "13 Apr 2025",
    time: "16:30",
    status: "upcoming",
    score: null,
  },
];
